- hosts: primarydomaincontroller
  roles:
    - role: justin_p.posh5
    - role: justin_p.wincom
    - role: justin_p.pdc
  post_tasks:
    - name: Ensure user gitlab_ldap_sync is present
      community.windows.win_domain_user:
        name: gitlab_ldap_sync
        password: "{{ pswd_gitlab_ldap_sync }}"
        state: present
        path: cn=Users,dc=ad,dc=domain,dc=test
    - name: Ensure OU Gitlab Users is present
      community.windows.win_domain_ou:
        name: GitlabUsers
        path: dc=ad,dc=domain,dc=test
        state: present
    - name: Ensure user test_user_in_pdc is present
      community.windows.win_domain_user:
        name: test_user_in_pdc
        password: "{{ pswd_test_user_in_pdc }}"
        state: present
        path: ou=GitlabUsers,dc=ad,dc=domain,dc=test

- hosts: gitlab
  become: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: buluma.gitlab
